{% set name = "hyram_test" %}
{% set version = "4.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ..
  sha256: a1356174052bc7b00892f1216e7bf4abd7e2bfe1027ad29d9ee64c2cdf315816

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6,<4.0
  run:
    - coolprop >=6.3
    - matplotlib-base
    - numpy
    - python >=3.6,<4.0
    - scipy

test:
  imports:
    - hyram
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://hyram.sandia.gov/
  summary: Hydrogen Plus Other Alternative Fuels Risk Assessment Models Python Package
  license: GPL-3.0
  license_file:
    - hyram_test.egg-info/COPYING.txt

extra:
  recipe-maintainers:
    - bliu1013