{% set name = "hyram" %}
{% set version = "4.1.1.post3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f9cd4d8341af1e91d16d969b239a74ec6cc699134e67cf4d7c220506920e4ab7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6,<4.0
  run:
    - coolprop >=6.3
    - matplotlib-base
    - numpy
    - python >=3.6,<4.0
    - scipy
    - pythonnet

test:
  imports:
    - hyram
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://hyram.sandia.gov/
  summary: Hydrogen Plus Other Alternative Fuels Risk Assessment Models Python Package
  license: GPL-3.0-only
  license_file:
    - hyram.egg-info/COPYING.txt

extra:
  recipe-maintainers:
    - bliu1013
